language: objective-c
osx_image: xcode7.2
env:
  global:
  - LC_CTYPE=en_US.UTF-8
  - LANG=en_US.UTF-8
  - PROJECT=MyFramework.xcodeproj
  - IOS_SCHEME="MyFrameworkiOS"
  - IOS_SDK=iphonesimulator9.2
  matrix:
    - DESTINATION="OS=9.2,name=iPhone 4S"        SCHEME="$IOS_SCHEME"     SDK="$IOS_SDK"     RUN_TESTS="YES" POD_LINT="YES"
before_script:
  - brew install swiftlint

script:
  - set -o pipefail
  - xcodebuild -version
  - xcodebuild -showsdks

  # Build Framework in Debug and Run Tests if specified
  - xcodebuild -project MyFramework.xcodeproj -scheme MyFrameworkiOS -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 6,OS=10.3.1' test

  # Run `pod lib lint` if specified
  - pod lib lint --allow-warnings --verbose;
