language: objective-c
osx_image: xcode7.2
env:
  global:
  - LC_CTYPE=en_US.UTF-8
  - LANG=en_US.UTF-8
  - PROJECT=MyFramework/MyFramework.xcodeproj
  - IOS_SCHEME="MyFrameworkiOS"
  - IOS_SDK=iphonesimulator9.2
  - OSX_SCHEME="MyFrameworkOSX"
  - OSX_SDK=macosx10.11
  - TVOS_SCHEME="MyFrameworkTVOS"
  - TVOS_SDK=appletvsimulator9.1
  matrix:
    - DESTINATION="OS=9.2,name=iPhone 4S"        SCHEME="$IOS_SCHEME"     SDK="$IOS_SDK"     RUN_TESTS="YES" POD_LINT="YES"
before_script:
  - brew install swiftlint

script:
  - set -o pipefail
  - xcodebuild -version
  - xcodebuild -showsdks

  # Build Framework in Debug and Run Tests if specified
  - xcodebuild -project "$PROJECT" -scheme "$SCHEME" -configuration Debug ONLY_ACTIVE_ARCH=NO test | xcpretty -c;

  # Run `pod lib lint` if specified
  # - if [ $POD_LINT == "YES" ]; then
  #     pod lib lint --private --verbose;
  #   fi
